"use strict";
const APP={name:"GIBDD-DPS",version:2,pageSize:12};
const state={stops:[],currentStopId:null,currentActionId:null,page:1,search:"",filters:{reason:"",action:"",dateFrom:"",dateTo:""},sort:{field:"date",direction:"desc"}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const uid=p=>`${p}_${crypto.randomUUID?crypto.randomUUID():Date.now()+"_"+Math.random().toString(36).slice(2)}`;
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const norm=v=>String(v??"").trim().toLowerCase().replace(/ё/g,"е");
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const reasonText=r=>({"0.1":"Проверка документов","0.2":"Нарушение ПДД / Дорожного кодекса","0.3":"Арест / задержание"}[r]||r||"—");
const actionText=t=>({fine:"Штраф",warning:"Предупреждение",arrest:"Арест / задержание",revocation:"Лишение"}[t]||t||"—");
const actionClass=t=>({fine:"badge-red",warning:"badge-gold",arrest:"badge-purple",revocation:"badge-blue"}[t]||"badge-blue");
const reasonClass=r=>({"0.1":"badge-blue","0.2":"badge-gold","0.3":"badge-red"}[r]||"badge-blue");
const resolutionText=(r,n)=>r==="not_issued"?"Постановление не выдано":r==="issued"?`Постановление № ${n||"—"}`:"";
let toastTimer;
function showToast(message,type="success"){const t=$("#toastMessage"),box=$("#toast"),icon=$("#toastIcon");if(!t)return;t.textContent=message;box.className=`toast show ${type}`;icon.setAttribute("class",type==="error"?"fa-solid fa-circle-xmark":type==="info"?"fa-solid fa-circle-info":"fa-solid fa-circle-check");clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.classList.remove("show"),3200)}
function openModal(id){const m=$("#"+id);if(!m)return;m.classList.add("active");document.body.style.overflow="hidden"}
function closeModal(id){const m=$("#"+id);if(!m)return;m.classList.remove("active");if(!document.querySelector(".modal-overlay.active"))document.body.style.overflow=""}
function normalizeAction(a={}){return{id:a.id||uid("act"),type:a.type||"fine",article:a.article||"",resolution:a.resolution||"",resolutionNumber:a.resolutionNumber||"",note:a.note||"",date:a.date||today(),createdAt:a.createdAt||new Date().toISOString()}}
function normalizeStop(s={}){return{id:s.id||uid("stop"),type:"stop",action:"Остановка",reason:s.reason||"0.1",make:s.make||"",color:s.color||"",plate:s.plate||"",owner:s.owner||"",passport:s.passport||"",license:s.license||"",date:s.date||today(),note:s.note||"",createdAt:s.createdAt||new Date().toISOString(),updatedAt:s.updatedAt||new Date().toISOString(),actions:Array.isArray(s.actions)?s.actions.map(normalizeAction):[]}}
function dbStopToState(r){return normalizeStop({id:r.id,reason:r.reason,make:r.make,color:r.color,plate:r.plate,owner:r.owner,passport:r.passport,license:r.license,date:r.game_date,note:r.note,createdAt:r.created_at,updatedAt:r.updated_at,actions:(r.actions||[]).map(a=>({id:a.id,type:a.type,article:a.article,resolution:a.resolution,resolutionNumber:a.resolution_number,note:a.note,date:a.game_date,createdAt:a.created_at}))})}
function stopDb(s){return{id:s.id,inspector_id:GIBDD_AUTH.inspector.id,reason:s.reason,make:s.make,color:s.color,plate:s.plate,owner:s.owner,passport:s.passport,license:s.license,game_date:s.date,note:s.note,created_at:s.createdAt,updated_at:s.updatedAt}}
function actionDb(stopId,a){return{id:a.id,stop_id:stopId,inspector_id:GIBDD_AUTH.inspector.id,type:a.type,article:a.article,resolution:a.resolution,resolution_number:a.resolutionNumber,note:a.note,game_date:a.date,created_at:a.createdAt}}
async function loadData(){const{data,error}=await sb.from("gibdd_stops").select("*, actions:gibdd_actions(*)").eq("inspector_id",GIBDD_AUTH.inspector.id).order("created_at",{ascending:false});if(error){console.error(error);showToast("Ошибка загрузки данных: "+error.message,"error");state.stops=[];return}state.stops=(data||[]).map(dbStopToState)}
async function saveStop(s){const{error}=await sb.from("gibdd_stops").upsert(stopDb(s),{onConflict:"id"});if(error)throw error;const{error:ae}=await sb.from("gibdd_actions").upsert((s.actions||[]).map(a=>actionDb(s.id,a)),{onConflict:"id"});if(ae)throw ae}
async function deleteStopRemote(id){const{error}=await sb.from("gibdd_stops").delete().eq("id",id).eq("inspector_id",GIBDD_AUTH.inspector.id);if(error)throw error}
async function deleteActionRemote(id){const{error}=await sb.from("gibdd_actions").delete().eq("id",id).eq("inspector_id",GIBDD_AUTH.inspector.id);if(error)throw error}
function updateStats(){const actions=state.stops.flatMap(s=>s.actions||[]);[["Stops",state.stops.length],["Actions",actions.length],["Fines",actions.filter(a=>a.type==="fine").length],["Warnings",actions.filter(a=>a.type==="warning").length],["Arrests",actions.filter(a=>a.type==="arrest").length],["Revocations",actions.filter(a=>a.type==="revocation").length]].forEach(([n,v])=>{const e=$("#stat"+n);if(e)e.textContent=v})}
function getFiltered(){let r=[...state.stops],q=norm(state.search);if(q)r=r.filter(s=>[s.owner,s.passport,s.license,s.plate,s.make,s.color,s.note,...(s.actions||[]).map(a=>[a.type,a.article,a.note,a.resolutionNumber].join(" "))].some(v=>norm(v).includes(q)));const f=state.filters;if(f.reason)r=r.filter(s=>s.reason===f.reason);if(f.action)r=r.filter(s=>f.action==="none"?!s.actions.length:s.actions.some(a=>a.type===f.action));if(f.dateFrom)r=r.filter(s=>s.date>=f.dateFrom);if(f.dateTo)r=r.filter(s=>s.date<=f.dateTo);r.sort((a,b)=>{const av=a[state.sort.field]||"",bv=b[state.sort.field]||"";return state.sort.direction==="asc"?String(av).localeCompare(String(bv)):String(bv).localeCompare(String(av))});return r}
function renderTable(){const rows=getFiltered(),pages=Math.max(1,Math.ceil(rows.length/APP.pageSize));if(state.page>pages)state.page=pages;const visible=rows.slice((state.page-1)*APP.pageSize,state.page*APP.pageSize);$("#tableBody").innerHTML=visible.length?visible.map(renderRow).join(""):`<tr><td colspan="9"><div class="empty"><i class="fa-solid fa-folder-open"></i><strong>${state.stops.length?"Ничего не найдено":"Журнал пуст"}</strong><span>${state.stops.length?"Измените параметры поиска или фильтров.":"Нажмите «Остановить ТС», чтобы создать первую запись."}</span></div></td></tr>`;$("#paginationInfo").textContent=rows.length?`Показано ${((state.page-1)*APP.pageSize)+1}–${Math.min(state.page*APP.pageSize,rows.length)} из ${rows.length}`:"0 записей";$("#paginationButtons").innerHTML=Array.from({length:pages},(_,i)=>`<button class="page-btn ${i+1===state.page?"active":""}" data-page="${i+1}">${i+1}</button>`).join("")}
function renderRow(s){const ac=s.actions||[];const actionsHtml=ac.length?ac.map(a=>`<span class="badge ${actionClass(a.type)}">${esc(actionText(a.type))}</span>`).join(" "):'<span class="muted">Нет</span>';const countHtml=ac.length?`<span class="action-count">${ac.length}</span>`:"";return `<tr data-open="${esc(s.id)}"><td>${esc(s.date)}</td><td><span class="badge ${reasonClass(s.reason)}">${esc(s.reason)} · ${esc(reasonText(s.reason))}</span></td><td><div class="cell-main">${esc(s.make)}</div><div class="cell-sub">${esc(s.color)} · <span class="plate">${esc(s.plate)}</span></div></td><td><div class="cell-main">${esc(s.owner)}</div></td><td>${esc(s.passport)}</td><td>${esc(s.license)}</td><td>${actionsHtml}${countHtml}</td><td><div class="note-cell">${esc(s.note||"—")}</div></td><td><div class="row-actions"><button class="btn-icon edit" data-edit="${esc(s.id)}"><i class="fa-solid fa-pen"></i></button><button class="btn-icon danger" data-delete="${esc(s.id)}"><i class="fa-solid fa-trash"></i></button></div></td></tr>`}
function renderAll(){updateStats();renderTable()}
function resetStopForm(){$("#stopForm").reset();$("#editStopId").value="";$("#stopDate").value=today();$("#stopModalTitle").innerHTML='<i class="fa-solid fa-stop-circle"></i> Остановка ТС';$("#stopModalSubtitle").textContent="Заполните данные остановки"}
function openCreateStop(){resetStopForm();openModal("stopModal");setTimeout(()=>$("#stopReason").focus(),100)}
function openEditStop(id){const s=state.stops.find(x=>x.id===id);if(!s)return;$("#editStopId").value=s.id;$("#stopReason").value=s.reason;$("#stopMake").value=s.make;$("#stopColor").value=s.color;$("#stopPlate").value=s.plate;$("#stopOwner").value=s.owner;$("#stopPassport").value=s.passport;$("#stopLicense").value=s.license;$("#stopDate").value=s.date;$("#stopNote").value=s.note;$("#stopModalTitle").innerHTML='<i class="fa-solid fa-pen"></i> Редактирование остановки';openModal("stopModal")}
async function submitStop(e){e.preventDefault();const id=$("#editStopId").value;const data=normalizeStop({id:id||uid("stop"),reason:$("#stopReason").value,make:$("#stopMake").value,color:$("#stopColor").value,plate:$("#stopPlate").value,owner:$("#stopOwner").value,passport:$("#stopPassport").value,license:$("#stopLicense").value,date:$("#stopDate").value,note:$("#stopNote").value});const old=state.stops.find(s=>s.id===id);if(old){data.actions=old.actions||[];data.createdAt=old.createdAt}if(id)state.stops[state.stops.findIndex(s=>s.id===id)]=data;else state.stops.unshift(data);try{await saveStop(data);closeModal("stopModal");renderAll();showToast(id?"Остановка обновлена":"Остановка создана")}catch(err){console.error(err);showToast("Ошибка сохранения: "+err.message,"error")}}
function openDetail(id){const s=state.stops.find(x=>x.id===id);if(!s)return;state.currentStopId=id;const actions=s.actions||[];$("#detailSubtitle").textContent=`${s.owner} · ${s.plate}`;$("#detailContent").innerHTML=`<div class="detail-section"><div class="info-grid"><div class="item"><span class="label">Причина остановки</span><span class="value"><span class="badge ${reasonClass(s.reason)}">${esc(s.reason)} — ${esc(reasonText(s.reason))}</span></span></div><div class="item"><span class="label">ТС</span><span class="value">${esc(s.make)} · ${esc(s.color)} <span class="plate">${esc(s.plate)}</span></span></div><div class="item"><span class="label">Владелец</span><span class="value">${esc(s.owner)}</span></div><div class="item"><span class="label">№ паспорта</span><span class="value">${esc(s.passport)}</span></div><div class="item"><span class="label">№ ВУ</span><span class="value">${esc(s.license)}</span></div><div class="item"><span class="label">День (игровой)</span><span class="value">${esc(s.date)}</span></div><div class="item full"><span class="label">Примечание</span><span class="value">${esc(s.note||"—")}</span></div></div><div style="display:flex;align-items:center;gap:12px;margin:16px 0 10px"><h3 style="font-size:16px;font-weight:700;color:#fff"><i class="fas fa-list"></i> Действия (${actions.length})</h3></div><div class="action-list">${actions.length?actions.map(renderAction).join(""):`<div class="empty"><i class="fa-solid fa-list"></i><span>Нет действий. Нажмите «Добавить действие».</span></div>`}</div></div>`;openModal("detailModal")}
function renderAction(a){return`<div class="action-item"><div><span class="badge ${actionClass(a.type)}">${esc(actionText(a.type))}</span> · ст. ${esc(a.article||"—")}${a.resolution?` · ${esc(resolutionText(a.resolution,a.resolutionNumber))}`:""}${a.note?` · ${esc(a.note)}`:""}</div><div class="row-actions"><button class="btn-icon edit" data-action-edit="${esc(a.id)}"><i class="fa-solid fa-pen"></i></button><button class="btn-icon danger" data-action-delete="${esc(a.id)}"><i class="fa-solid fa-trash"></i></button></div></div>`}
function fillActionModal(a=null){const s=state.stops.find(x=>x.id===state.currentStopId);if(!s)return;state.currentActionId=a?.id||null;$("#actionStopId").value=s.id;$("#actionOwner").textContent=s.owner||"—";$("#actionPassport").textContent=s.passport||"—";$("#actionLicense").textContent=s.license||"—";$("#actionVehicle").textContent=`${s.make} · ${s.color||""}`;$("#actionDate").textContent=s.date||"—";$("#actionPlate").textContent=s.plate||"—";$("#actionType").value=a?.type||"";$("#actionArticle").value=a?.article||"";$("#actionResolution").value=a?.resolution||"";$("#actionResolutionNumber").value=a?.resolutionNumber||"";$("#actionNote").value=a?.note||"";$("#editActionId").value=a?.id||"";toggleResolution();$("#actionModalTitle").innerHTML=a?'<i class="fa-solid fa-pen"></i> Редактирование действия':'<i class="fa-solid fa-gavel"></i> Добавить действие';openModal("actionModal")}
function toggleResolution(){$("#resolutionGroup").classList.toggle("hidden",$("#actionType").value!=="fine")}
async function submitAction(e){e.preventDefault();const s=state.stops.find(x=>x.id===state.currentStopId);if(!s)return;const a=normalizeAction({id:state.currentActionId||uid("act"),type:$("#actionType").value,article:$("#actionArticle").value,resolution:$("#actionResolution").value,resolutionNumber:$("#actionResolutionNumber").value,note:$("#actionNote").value,date:s.date});if(state.currentActionId){const i=s.actions.findIndex(x=>x.id===state.currentActionId);s.actions[i]=a}else s.actions.push(a);s.updatedAt=new Date().toISOString();try{await saveStop(s);closeModal("actionModal");openDetail(s.id);renderAll();showToast("Действие сохранено")}catch(err){showToast("Ошибка сохранения действия: "+err.message,"error")}}
async function removeStop(id){if(!confirm("Удалить остановку и все связанные действия?"))return;try{await deleteStopRemote(id);state.stops=state.stops.filter(s=>s.id!==id);closeModal("detailModal");renderAll();showToast("Остановка удалена","error")}catch(e){showToast("Ошибка удаления: "+e.message,"error")}}
async function removeAction(id){const s=state.stops.find(x=>x.id===state.currentStopId);if(!s||!confirm("Удалить это действие?"))return;try{await deleteActionRemote(id);s.actions=s.actions.filter(a=>a.id!==id);openDetail(s.id);renderAll();showToast("Действие удалено","error")}catch(e){showToast("Ошибка удаления: "+e.message,"error")}}
function openSearchModal(preset=""){$("#searchPassportInput").value=preset;$("#searchResults").innerHTML='<div class="empty"><i class="fa-solid fa-user-shield"></i><strong>Поиск гражданина</strong><span>Введите номер паспорта и нажмите «Искать».</span></div>';openModal("searchModal");if(preset)performSearch();setTimeout(()=>$("#searchPassportInput").focus(),100)}
function performSearch(){const q=norm($("#searchPassportInput").value);if(!q)return showToast("Введите номер паспорта","error");const r=state.stops.filter(s=>norm(s.passport).includes(q));$("#searchResults").innerHTML=r.length?r.map(s=>`<div class="result-card"><div class="result-head"><div><div class="result-owner">${esc(s.owner)}</div><div class="muted">${esc(s.passport)} · ${esc(s.plate)}</div></div><div class="result-date">${esc(s.date)}</div></div><div class="result-vehicle">${esc(s.make)} · ${esc(s.color)} · ${s.actions.length} действий</div><div class="result-actions"><button class="btn btn-secondary btn-sm" data-search-open="${esc(s.id)}">Открыть</button><button class="btn btn-secondary btn-sm" data-search-edit="${esc(s.id)}">Изменить</button></div></div>`).join(""):`<div class="empty"><i class="fa-solid fa-user-slash"></i><strong>Ничего не найдено</strong><span>По паспорту «${esc(q)}» записей нет.</span></div>`}
function exportData(){const blob=new Blob([JSON.stringify(state.stops,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`gibdd_export_${today()}.json`;a.click();URL.revokeObjectURL(a.href);showToast("Данные выгружены")}
function printRecord(){const s=state.stops.find(x=>x.id===state.currentStopId);if(!s)return;const w=open("","_blank","width=800,height=700");if(!w)return;w.document.write(`<html><head><title>ГИБДД · ${esc(s.plate)}</title><style>body{font:14px Arial;padding:30px}h1{font-size:22px}.row{padding:8px 0;border-bottom:1px solid #ddd}.label{color:#777;display:inline-block;width:180px}.act{margin:12px 0;padding:10px;background:#f3f3f3}</style></head><body><h1>ГИБДД · ДПС — Остановка ТС</h1><div class="row"><span class="label">Дата</span>${esc(s.date)}</div><div class="row"><span class="label">Причина</span>${esc(reasonText(s.reason))}</div><div class="row"><span class="label">ТС</span>${esc(s.make)} · ${esc(s.color)} · ${esc(s.plate)}</div><div class="row"><span class="label">Владелец</span>${esc(s.owner)}</div><div class="row"><span class="label">Паспорт</span>${esc(s.passport)}</div><div class="row"><span class="label">ВУ</span>${esc(s.license)}</div>${(s.actions||[]).map(a=>`<div class="act"><b>${esc(actionText(a.type))}</b> · ст. ${esc(a.article)} ${esc(resolutionText(a.resolution,a.resolutionNumber))}<br>${esc(a.note)}</div>`).join("")}<script>window.print()</script></body></html>`);w.document.close()}
async function importData(e){const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d)||d.some(x=>!x.id||!x.reason)){showToast("Неверный формат данных","error");return}if(!confirm(`Заменить ${state.stops.length} записей на ${d.length}?`))return;const records=d.map(normalizeStop),inspector=GIBDD_AUTH.inspector.id;let r=await sb.from("gibdd_actions").delete().eq("inspector_id",inspector);if(r.error)throw r.error;r=await sb.from("gibdd_stops").delete().eq("inspector_id",inspector);if(r.error)throw r.error;if(records.length){r=await sb.from("gibdd_stops").insert(records.map(stopDb));if(r.error)throw r.error;const acts=records.flatMap(s=>s.actions.map(a=>actionDb(s.id,a)));if(acts.length){r=await sb.from("gibdd_actions").insert(acts);if(r.error)throw r.error}}state.stops=records;renderAll();showToast("Данные импортированы")}catch(err){console.error(err);showToast("Ошибка импорта: "+err.message,"error")}finally{e.target.value=""}}
function bind(){$("#btnCreateStop").onclick=openCreateStop;$("#btnSearch").onclick=()=>openSearchModal();$("#btnBackup").onclick=exportData;$("#btnExport").onclick=exportData;$("#btnImport").onclick=()=>$("#fileInput").click();$("#fileInput").onchange=importData;$("#btnResetFilters").onclick=()=>{$("#filterReason").value="";$("#filterAction").value="";$("#filterDateFrom").value="";$("#filterDateTo").value="";state.filters={reason:"",action:"",dateFrom:"",dateTo:""};state.page=1;renderAll()};$("#btnApplyFilters").onclick=()=>{state.filters={reason:$("#filterReason").value,action:$("#filterAction").value,dateFrom:$("#filterDateFrom").value,dateTo:$("#filterDateTo").value};state.page=1;renderAll()};$("#tableSearch").oninput=e=>{state.search=e.target.value;state.page=1;renderTable()};$("#stopForm").onsubmit=submitStop;$("#actionForm").onsubmit=submitAction;$("#actionType").onchange=toggleResolution;$("#btnAddAction").onclick=()=>fillActionModal();$("#btnDeleteDetail").onclick=()=>removeStop(state.currentStopId);$("#btnPrintRecord").onclick=printRecord;$("#btnSearchFromStop").onclick=()=>openSearchModal($("#stopPassport").value);$("#btnPerformSearch").onclick=performSearch;$("#btnShareRecord").onclick=()=>{const s=state.stops.find(x=>x.id===state.currentStopId);if(!s)return;navigator.clipboard?.writeText(`${location.href.split("#")[0]}#stop=${s.id}`);showToast("Ссылка скопирована")};$("#paginationButtons").onclick=e=>{const b=e.target.closest("[data-page]");if(b){state.page=+b.dataset.page;renderTable()}};$("#tableBody").onclick=e=>{const del=e.target.closest("[data-delete]"),edit=e.target.closest("[data-edit]"),row=e.target.closest("tr[data-open]");if(del)return removeStop(del.dataset.delete);if(edit)return openEditStop(edit.dataset.edit);if(row)return openDetail(row.dataset.open)};$("#detailContent").onclick=e=>{const ed=e.target.closest("[data-action-edit]"),del=e.target.closest("[data-action-delete]");if(ed){const s=state.stops.find(x=>x.id===state.currentStopId);fillActionModal(s?.actions.find(a=>a.id===ed.dataset.actionEdit))}if(del)removeAction(del.dataset.actionDelete)};$("#searchResults").onclick=e=>{const o=e.target.closest("[data-search-open]"),ed=e.target.closest("[data-search-edit]");if(o){closeModal("searchModal");openDetail(o.dataset.searchOpen)}if(ed){closeModal("searchModal");openEditStop(ed.dataset.searchEdit)}};$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('th.sortable').forEach(th=>th.onclick=()=>{const f=th.dataset.sort;state.sort.direction=state.sort.field===f&&state.sort.direction==='asc'?'desc':'asc';state.sort.field=f;renderTable()});document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal-overlay.active').forEach(m=>closeModal(m.id));if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();openSearchModal()}if(e.ctrlKey&&e.key.toLowerCase()==='n'){e.preventDefault();openCreateStop()}})}
async function init(){bind();await loadData();renderAll();const hash=location.hash.match(/stop=([^&]+)/);if(hash&&state.stops.some(s=>s.id===hash[1]))openDetail(hash[1]);console.log("🚔 GIBDD-DPS v2 + Supabase initialized")}
window.initGibddApp=init;