const TABLES={vehicles:{title:'Автомобиль',table:'vehicles',fields:[['plate','Госномер','text',true],['vin','VIN','text',false],['brand','Марка','text',true],['model','Модель','text',true],['color','Цвет','text',false],['year','Год','number',false],['owner_name','Владелец','text',false]]},drivers:{title:'Водитель',table:'drivers',fields:[['full_name','ФИО','text',true],['birth_date','Дата рождения','date',false],['license_number','Номер удостоверения','text',true],['license_category','Категория','text',false],['phone','Телефон','text',false],['address','Адрес','text',false]]},protocols:{title:'Протокол',table:'protocols',fields:[['number','Номер протокола','text',true],['violation_date','Дата нарушения','datetime-local',true],['driver_name','Водитель','text',true],['plate','Госномер','text',true],['article','Статья','text',true],['description','Описание','textarea',true],['amount','Сумма','number',false]]},fines:{title:'Штраф',table:'fines',fields:[['number','Номер постановления','text',true],['issued_at','Дата','datetime-local',true],['driver_name','Водитель','text',true],['plate','Госномер','text',true],['article','Статья','text',true],['amount','Сумма','number',true],['status','Статус','select',true,['Не оплачен','Оплачен','Отменён']]]}};
let currentType=null,currentId=null,cache={vehicles:[],drivers:[],protocols:[],fines:[]};
const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const fmt=v=>v?new Date(v).toLocaleString('ru-RU'):'—';
function toast(t,bad=false){const e=document.getElementById('toast');e.textContent=t;e.className='toast show '+(bad?'bad':'ok');clearTimeout(window._toast);window._toast=setTimeout(()=>e.className='toast',2800)}
function tableHtml(type,rows){if(!rows.length)return '<div class="empty">Записей пока нет.</div>';const cfg=TABLES[type];const cols=cfg.fields.map(x=>x[0]);return `<table class="table"><thead><tr>${cfg.fields.slice(0,5).map(x=>`<th>${esc(x[1])}</th>`).join('')}<th>Дата</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.slice(0,5).map(c=>`<td>${c.includes('date')||c.endsWith('_at')||c.includes('violation')?esc(fmt(r[c])):c==='amount'?esc(r[c]??'')+' ₽':c==='status'?`<span class="badge ${r[c]==='Оплачен'?'paid':''}">${esc(r[c]||'Не оплачен')}</span>`:esc(r[c])}</td>`).join('')}<td>${fmt(r.created_at)}</td><td><div class="actions"><button class="btn-icon" data-edit="${type}" data-id="${r.id}"><i class="fa-solid fa-pen"></i></button><button class="btn-icon" data-delete="${type}" data-id="${r.id}"><i class="fa-solid fa-trash"></i></button></div></td></tr>`).join('')}</tbody></table>`}
async function load(type){const cfg=TABLES[type];const {data,error}=await sb.from(cfg.table).select('*').order('created_at',{ascending:false});if(error){toast(error.message,true);return}cache[type]=data||[];document.getElementById(type+'Table').innerHTML=tableHtml(type,cache[type]);updateStats();renderRecent();}
async function loadAll(){await Promise.all(Object.keys(TABLES).map(load))}
function updateStats(){for(const t of Object.keys(TABLES))document.getElementById('stat'+t[0].toUpperCase()+t.slice(1)).textContent=cache[t].length;document.getElementById('statPaid').textContent=cache.fines.filter(x=>x.status==='Оплачен').length}
function renderRecent(){const all=Object.entries(cache).flatMap(([type,rows])=>rows.map(r=>({...r,_type:type}))).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,12);document.getElementById('recentList').innerHTML=all.length?`<table class="table"><thead><tr><th>Раздел</th><th>Основная информация</th><th>Создано</th></tr></thead><tbody>${all.map(r=>`<tr><td>${TABLES[r._type].title}</td><td>${esc(r.number||r.plate||r.license_number||r.full_name||'—')}</td><td>${fmt(r.created_at)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">История пуста.</div>'}
function openModal(type,row=null){currentType=type;currentId=row?.id||null;const cfg=TABLES[type];document.getElementById('modalTitle').textContent=(row?'Редактировать ':'Добавить ')+cfg.title;document.getElementById('formFields').innerHTML=cfg.fields.map(f=>{let [name,label,kind,req,opts]=f;let value=row?.[name]??'';if(kind==='select')return `<label>${esc(label)}<select class="select" name="${name}" ${req?'required':''}>${opts.map(o=>`<option ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;return `<label class="${kind==='textarea'?'full':''}">${esc(label)}<${kind==='textarea'?'textarea':'input'} class="${kind==='textarea'?'textarea':'input'}" name="${name}" type="${kind==='textarea'?'text':kind}" value="${kind==='textarea'?'':esc(value)}" ${req?'required':''}>${kind==='textarea'?esc(value):''}</${kind==='textarea'?'textarea':'input'}></label>`}).join('');document.getElementById('modal').classList.remove('hidden')}
async function save(e){e.preventDefault();const fd=new FormData(e.target),payload={};TABLES[currentType].fields.forEach(f=>{let v=fd.get(f[0]);payload[f[0]]=v===''?null:(f[2]==='number'?Number(v):v)});payload.inspector_id=GIBDD_AUTH.inspector.id;let q;if(currentId)q=sb.from(TABLES[currentType].table).update(payload).eq('id',currentId);else q=sb.from(TABLES[currentType].table).insert(payload);const {error}=await q;if(error){toast(error.message,true);return}closeModal();toast('Данные сохранены');await load(currentType)}
async function remove(type,id){if(!confirm('Удалить запись?'))return;const {error}=await sb.from(TABLES[type].table).delete().eq('id',id);if(error){toast(error.message,true);return}toast('Запись удалена');await load(type)}
function closeModal(){document.getElementById('modal').classList.add('hidden');document.getElementById('entityForm').reset();currentId=null}
function tab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===name))}
window.addEventListener('gibdd:ready',loadAll);
document.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
 document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add)openModal(add.dataset.add);const edit=e.target.closest('[data-edit]');if(edit){const row=cache[edit.dataset.edit].find(x=>String(x.id)===String(edit.dataset.id));if(row)openModal(edit.dataset.edit,row)}const del=e.target.closest('[data-delete]');if(del)remove(del.dataset.delete,del.dataset.id)});
 document.getElementById('entityForm').addEventListener('submit',save);document.getElementById('modalClose').onclick=closeModal;document.getElementById('modalCancel').onclick=closeModal;document.getElementById('profileBtn').onclick=()=>{const p=GIBDD_AUTH.inspector;alert(`Инспектор\n\nФИО: ${p.full_name}\nНомер: ${p.badge_number||'—'}\nЗвание: ${p.rank||'—'}\nПодразделение: ${p.department||'—'}\nДолжность: ${p.position||'—'}`)};
 document.getElementById('globalSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();for(const type of Object.keys(TABLES)){const filtered=cache[type].filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(q)));document.getElementById(type+'Table').innerHTML=tableHtml(type,filtered)}});
});
